name = "whereami-api"
compatibility_date = "2025-05-30"
compatibility_flags = ["nodejs_compat"]

# Pages configuration (no main field needed for Pages Functions)
pages_build_output_dir = ".svelte-kit/cloudflare"

# Single R2 bucket for all environments
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "whereami-images"

# Single set of KV namespaces for all environments
[[kv_namespaces]]
binding = "GAME_METADATA"
id = "b2d844556c024af599a55f653d38ea09"

[[kv_namespaces]]
binding = "USER_DATA"
id = "871c412270ad49a88db04e146bee26c8"

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
MAX_FILE_SIZE = "10485760"  # 10MB
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp"
# Supabase Authentication
PUBLIC_SUPABASE_URL = "https://vcgwduccreqwwvljprie.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZ3dkdWNjcmVxd3d2bGpwcmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Njc4MjEsImV4cCI6MjA2NDM0MzgyMX0.99zmZlIIyh4tpVuFKz-GIN6P78gqVnLN6Be0NXHTEWU" 