name = "whereami"
compatibility_date = "2025-05-30"
compatibility_flags = ["nodejs_compat"]

# Pages configuration (no main field needed for Pages Functions)
pages_build_output_dir = ".svelte-kit/cloudflare"

# R2 bucket for images
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "whereami-images"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "whereami-db"
database_id = "c0b31999-8a8b-4a05-b63d-c3e81e19f504"  # You'll need to create this with: wrangler d1 create whereami-db

# KV namespaces (shared between prod and dev)
[[kv_namespaces]]
binding = "IMAGE_DATA"
id = "ed09b9a23eeb4a58b500f03e636ea811"

[[kv_namespaces]]
binding = "USER_DATA"
id = "7fb86fe8775e461996350c8f2dc6f86b"

[[kv_namespaces]]
binding = "GAME_DATA"
id = "8b8aaaeb40844b2c9591c98860b9dd47"

# Variables
[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
MAX_FILE_SIZE = "10485760"  # 10MB
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp"
PUBLIC_SUPABASE_URL = "https://vcgwduccreqwwvljprie.supabase.co"